# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IU7StVJ70QDjTnmxwiQrxSIfEVuc8JFz
"""

import sympy as sp

def matematik_hisob_kitob():
    print("Matematik hisob-kitoblar dasturiga xush kelibsiz!")
    print("Quyidagi funksiyalardan foydalanishingiz mumkin:")
    print("1. Oddiy arifmetik amallar (yig'indi, ayirma, ko'paytma, bo'lish)")
    print("2. Algebraik ifodalar (soddalashtirish, hosila, integral)")
    print("3. Tenglamalarni yechish")

    while True:
        print("\nKerakli amalni tanlang: ")
        print("1 - Arifmetik amallar")
        print("2 - Algebraik ifodalar")
        print("3 - Tenglamani yechish")
        print("4 - Chiqish")

        tanlov = input("Tanlovingizni kiriting: ")

        if tanlov == "1":
            amal = input("Arifmetik ifodani kiriting (masalan, 2 + 3 * 4): ")
            try:
                natija = eval(amal)
                print(f"Natija: {natija}")
            except Exception as e:
                print(f"Xatolik yuz berdi: {e}")

        elif tanlov == "2":
            ifoda = input("Algebraik ifodani kiriting (masalan, x**2 + 2*x + 1): ")
            x = sp.Symbol('x')
            try:
                ifoda_s = sp.sympify(ifoda)
                print(f"Soddalashtirilgan ifoda: {sp.simplify(ifoda_s)}")
                print(f"Hosila: {sp.diff(ifoda_s, x)}")
                print(f"Integrali: {sp.integrate(ifoda_s, x)}")
            except Exception as e:
                print(f"Xatolik yuz berdi: {e}")

        elif tanlov == "3":
            tenglama = input("Tenglamani kiriting (masalan, x**2 - 4): ")
            try:
                tenglama_s = sp.sympify(tenglama)
                yechimlar = sp.solve(tenglama_s, x)
                print(f"Tenglama yechimlari: {yechimlar}")
            except Exception as e:
                print(f"Xatolik yuz berdi: {e}")

        elif tanlov == "4":
            print("Dasturdan chiqmoqdasiz. Xayr!")
            break

        else:
            print("Noto'g'ri tanlov, qayta urinib ko'ring.")

# Dasturni ishga tushirish
matematik_hisob_kitob()